"""feat: Multiplayer Models & Auth

Revision ID: af2b32a164cd
Revises:
Create Date: 2026-04-06 20:18:09.241693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af2b32a164cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('game_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('LOBBY', 'ACTIVE', 'ENDED', name='gamesessionstatus'), nullable=False),
    sa.Column('current_battlemap_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('game_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_faction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relations_politiques', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_location',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points_interet', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_npc',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('nom', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('faction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('is_in_combat', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessionparticipants',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_session.id'], ),
    sa.PrimaryKeyConstraint('character_id', 'session_id')
    )
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('universe_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('known_spells', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('spell_slots', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('class_resources', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.create_foreign_key('fk_character_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_character_universe_id', 'universe', ['universe_id'], ['id'])
        batch_op.drop_column('battlemap_image_url')
        batch_op.drop_column('game_mode')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_mode', sa.VARCHAR(), server_default=sa.text("'NARRATIVE'"), nullable=False))
        batch_op.add_column(sa.Column('battlemap_image_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_character_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_character_universe_id', type_='foreignkey')
        batch_op.drop_column('class_resources')
        batch_op.drop_column('spell_slots')
        batch_op.drop_column('known_spells')
        batch_op.drop_column('user_id')
        batch_op.drop_column('universe_id')

    op.drop_table('sessionparticipants')
    op.drop_table('world_npc')
    op.drop_table('world_location')
    op.drop_table('world_faction')
    op.drop_table('game_session')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('universe')
    # ### end Alembic commands ###
