"""Add inventory tables

Revision ID: b2f810029ab6
Revises: e1b2cd8019e2
Create Date: 2026-04-12 17:49:18.623373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2f810029ab6'
down_revision: Union[str, Sequence[str], None] = 'e1b2cd8019e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_slot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('universe_id', sa.Uuid(), nullable=False))
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('attributes', sa.JSON(), nullable=True))
        batch_op.drop_constraint('item_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_item_universe_id_universe', 'universe', ['universe_id'], ['id'])
        batch_op.drop_column('quantity')
        batch_op.drop_column('character_id')
        batch_op.drop_column('damage_dice')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('damage_dice', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.CHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_item_universe_id_universe', type_='foreignkey')
        batch_op.create_foreign_key('fk_item_character_id_character', 'character', ['character_id'], ['id'])
        batch_op.drop_column('attributes')
        batch_op.drop_column('description')
        batch_op.drop_column('universe_id')

    op.drop_table('inventory_slot')
    # ### end Alembic commands ###
